### ISSUE TITLE
Front-end: Login Screen

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#12]
### Tasks

- [ ] App logo should render on top half of the screen
- [x] Create option to login with email
- [x] Create option to login with Google
- [x] Sign up with Email/password
- [ ] Add a forgot password link to the bottom
