### ISSUE TITLE
View: Restaurant Details Screen

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#14]
### Tasks
- [x] Image 
- [x] Display cuisine, price range, address
- [x] Display preview of menu items
- [x] Back button to return to home screen
