### ISSUE TITLE
View: Profile Screen

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#15]
### Tasks
** A user can:**
- [x] see their profile image
- [x] see basic information about themselves
- [x] see a button to manage settings
- [x] see a button to manage notifications
- [x] see a list of all their friends
