### ISSUE TITLE
CHORE: Abstract components

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#24]
### Tasks
- [x] Abstract Navbar to its own class
- [x] Abstract Routes to separate class
- [x] Bring Router to highest file level possible
- [x] Fix PWA icon for iOS
