### ISSUE TITLE
Can view friends pulled from the Firestore

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#46]
### Tasks
- [x] Refactor friend list to display real data
- [x] Thunk for getting friends
- [x] Pulls a specific users friends subcollection
