### ISSUE TITLE
Can find other users and send a friend request

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#47]
### Tasks
- [x] Search the Firestore for users by name
- [x] Select from a list of users to send requests
- [x] Receive visual feedback that a user is selected
- [x] Send a friend request to other users
