### ISSUE TITLE
Can set a location

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#7]
### Tasks
- [ ] Implement PWA Geo-location
- [ ] **Allow user to choose between:**
   - [ ] Manually selecting
   - [ ] Opting into location services
