### ISSUE TITLE
Can swipe through same restaurants as friend

### ISSUE THREAD

**Issue by abielik** [Keep-it-on-the-Download/hangry#73]
### Tasks
- [x] **Sync Redux and Firestore**
   - [x] Add logic to get more restaurants
   - [x] increment pointer when swiping
