### ISSUE TITLE
Can find a matching restaurant with friend

### ISSUE THREAD

**Issue by abielik** [Keep-it-on-the-Download/hangry#74]
### Tasks
- [x] Add selected restaurants to shared Firestore
- [x] Check Firestore for if a restaurant already exists
- [x] Provide a popup or alert when matching happens
- [x] Popup dialog provides button to redirect user to matched restaurant details
- [ ] Provide persistent status on active party list
