### ISSUE TITLE
Can receive notifications

### ISSUE THREAD

**Issue by abielik** [Keep-it-on-the-Download/hangry#75]
### Tasks
- [ ] Implement notification system that works regardless of current screen
- [ ] **Provide notifications for:**
   - [ ] Accepted friend requests
   - [ ] Accepted party requests
   - [ ] Matches
- [ ] Implement as PWA push notifications
