### ISSUE TITLE
Can swipe through restaurants

### ISSUE THREAD

**Issue by CharlesDell** [Keep-it-on-the-Download/hangry#8]
### Tasks
- [x] **Restaurant Cards**
   - [x] Renders restaurant data from yelp API
   - [x] Displays an image (or set or images)
   - [x] Displays restaurant name
   - [x] Displays price range
- [x] **Card actions**
   - [x] Swipe to approve or reject
   - [x] Have button alternatives
